on:
  push:
    branches:
      - main

jobs:

 build-github-registry:
   runs-on: ubuntu-latest
   steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
         cache: maven
     - name: Set up Maven
       uses: stCarolas/setup-maven@v4.2
       with:
         maven-version: 3.8.2
     - name: "mvn: native package"
       run: |-
         mvn clean package -Pnative -Dquarkus.native.container-build=true
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: GitHub Packages login
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.PAT }}
     - name: Push to GitHub Packages
       uses: docker/build-push-action@v2
       with:
         push: true
         file: src/main/docker/Dockerfile.native
         context: ${{ github.workspace }}
         platforms: ${{ env.PLATFORMS }}
         tags: ghcr.io/tmarmillot/communication-with-quarkus:latest